language: node_js
node_js:
- '6'
env:
  JSTAG_VERSION: $(git rev-parse HEAD)
cache:
  directories:
  - travis_phantomjs
before_install:
- openssl aes-256-cbc -K $encrypted_12a92b7fdcf8_key -iv $encrypted_12a92b7fdcf8_iv
  -in LIO-staging-lytics-js.json.enc -out LIO-staging-lytics-js.json -d
- ./bin/cache-phantom
before_script:
- npm install -g gulp
script: gulp release
repo_token: piyOM4c71ZPWZiPAbkCWUqrhColI2nSW7
deploy:
  provider: gcs
  local_dir: out
  access_key_id: GOOGDGAEWNWX3SXOYPUI
  secret_access_key:
    secure: FQoimbN5Q3udVG/O1BY1+xfbVRZX8aKMnS+p/hEWp86gQzXZDTrht2F6JY81Kmr7JCUylB/5Ma+TeQxz6kgduuLECS0tSVnH/P+4TdwUw8AXrtLDnwZ7umOlT8F1DupNcbgleLKNXE+krI7+b1RJ9gUHkyvOOZ5zD8/gaDkw9Ls=
  project: lyticsstaging
  bucket: lytics-js
  skip_cleanup: true
  on: master2
