#!/usr/bin/env bash

echo "Create iow.js"
cat src/files/shim.js src/files/io.js  > src/files/iow.js

echo "minify async.js"
uglifyjs -o src/files/async.min.js src/files/async.js
cp src/files/async.min.js out/async.min.js

echo "Minify io.js"
uglifyjs -o src/files/io.min.js src/files/io.js
uglifyjs -o out/io.min.js src/files/io.js

echo "Minify iow.js "
uglifyjs -o src/files/iow.min.js src/files/iow.js
cp src/files/iow.min.js out/iow.min.js

# go ahead and run docpad generate just in case
docpad generate
