#!/usr/bin/env bash

echo "minify async.js"
uglifyjs -o src/async2.min.js src/async2.js
cp src/async2.min.js out/async2.min.js

uglifyjs -o src/async.min.js src/async.js
cp src/async.min.js out/async.min.js

uglifyjs -o src/async.lite.min.js src/async.lite.js
cp src/async.lite.min.js out/async.lite.min.js

echo "Minify io.js"
uglifyjs -o src/io.min.js src/io.js
uglifyjs -o out/io.min.js src/io.js
cp src/io.js out/io.js

echo "Minify io.lite.js"
uglifyjs -o src/io.lite.min.js src/io.lite.js
uglifyjs -o out/io.lite.min.js src/io.lite.js

# go ahead and run docpad generate just in case
# use the env=static to remove live-reload
#docpad generate --env static

echo "Copy js files to examples"
mkdir -p examples
cp out/async.js examples/async.js
cp out/async.lite.js examples/async.lite.js
cp out/async.lite.min.js examples/async.lite.min.js
cp out/io.min.js examples/io.min.js
cp src/io.js examples/io.js
