const JSTAG_DIST_DIR           = process.env.JSTAG_DIST_DIR || 'out';
const JSTAG_COVERAGE_DIR       = process.env.JSTAG_COVERAGE_DIR || 'coverage';
const COVERALLS_REPO_TOKEN     = process.env.COVERALLS_REPO_TOKEN;

const JSTAG_DIST_LEGACY_DIR    = process.env.JSTAG_DIST_LEGACY_DIR || `${JSTAG_DIST_DIR}/legacy`;
const JSTAG_DIST_MODERN_DIR    = process.env.JSTAG_DIST_MODERN_DIR || `${JSTAG_DIST_DIR}/v3`;
const JSTAG_DIST_DEV_DIR       = process.env.JSTAG_DIST_DEV_DIR || `${JSTAG_DIST_MODERN_DIR}/dev`;
const JSTAG_DIST_RELEASE_DIR   = process.env.JSTAG_DIST_RELEASE_DIR || `${JSTAG_DIST_MODERN_DIR}/latest`;
const JSTAG_COVERAGE_ASYNC_DIR = process.env.JSTAG_COVERAGE_ASYNC_DIR || `${JSTAG_COVERAGE_DIR}/async`;

module.exports = {
  JSTAG_DIST_DIR,
  JSTAG_DIST_LEGACY_DIR,
  JSTAG_DIST_MODERN_DIR,
  JSTAG_DIST_DEV_DIR,
  JSTAG_DIST_RELEASE_DIR,

  JSTAG_COVERAGE_DIR,
  JSTAG_COVERAGE_ASYNC_DIR,

  COVERALLS_REPO_TOKEN,
};
